	soc_system u0 (
		.clk_clk                          (<connected-to-clk_clk>),                          //       clk.clk
		.clk_100m_clk                     (<connected-to-clk_100m_clk>),                     //  clk_100m.clk
		.d_out_in                         (<connected-to-d_out_in>),                         //     d_out.in
		.d_out_out                        (<connected-to-d_out_out>),                        //          .out
		.d_out_oe                         (<connected-to-d_out_oe>),                         //          .oe
		.hps_io_hps_io_emac1_inst_TX_CLK  (<connected-to-hps_io_hps_io_emac1_inst_TX_CLK>),  //    hps_io.hps_io_emac1_inst_TX_CLK
		.hps_io_hps_io_emac1_inst_TXD0    (<connected-to-hps_io_hps_io_emac1_inst_TXD0>),    //          .hps_io_emac1_inst_TXD0
		.hps_io_hps_io_emac1_inst_TXD1    (<connected-to-hps_io_hps_io_emac1_inst_TXD1>),    //          .hps_io_emac1_inst_TXD1
		.hps_io_hps_io_emac1_inst_TXD2    (<connected-to-hps_io_hps_io_emac1_inst_TXD2>),    //          .hps_io_emac1_inst_TXD2
		.hps_io_hps_io_emac1_inst_TXD3    (<connected-to-hps_io_hps_io_emac1_inst_TXD3>),    //          .hps_io_emac1_inst_TXD3
		.hps_io_hps_io_emac1_inst_RXD0    (<connected-to-hps_io_hps_io_emac1_inst_RXD0>),    //          .hps_io_emac1_inst_RXD0
		.hps_io_hps_io_emac1_inst_MDIO    (<connected-to-hps_io_hps_io_emac1_inst_MDIO>),    //          .hps_io_emac1_inst_MDIO
		.hps_io_hps_io_emac1_inst_MDC     (<connected-to-hps_io_hps_io_emac1_inst_MDC>),     //          .hps_io_emac1_inst_MDC
		.hps_io_hps_io_emac1_inst_RX_CTL  (<connected-to-hps_io_hps_io_emac1_inst_RX_CTL>),  //          .hps_io_emac1_inst_RX_CTL
		.hps_io_hps_io_emac1_inst_TX_CTL  (<connected-to-hps_io_hps_io_emac1_inst_TX_CTL>),  //          .hps_io_emac1_inst_TX_CTL
		.hps_io_hps_io_emac1_inst_RX_CLK  (<connected-to-hps_io_hps_io_emac1_inst_RX_CLK>),  //          .hps_io_emac1_inst_RX_CLK
		.hps_io_hps_io_emac1_inst_RXD1    (<connected-to-hps_io_hps_io_emac1_inst_RXD1>),    //          .hps_io_emac1_inst_RXD1
		.hps_io_hps_io_emac1_inst_RXD2    (<connected-to-hps_io_hps_io_emac1_inst_RXD2>),    //          .hps_io_emac1_inst_RXD2
		.hps_io_hps_io_emac1_inst_RXD3    (<connected-to-hps_io_hps_io_emac1_inst_RXD3>),    //          .hps_io_emac1_inst_RXD3
		.hps_io_hps_io_qspi_inst_IO0      (<connected-to-hps_io_hps_io_qspi_inst_IO0>),      //          .hps_io_qspi_inst_IO0
		.hps_io_hps_io_qspi_inst_IO1      (<connected-to-hps_io_hps_io_qspi_inst_IO1>),      //          .hps_io_qspi_inst_IO1
		.hps_io_hps_io_qspi_inst_IO2      (<connected-to-hps_io_hps_io_qspi_inst_IO2>),      //          .hps_io_qspi_inst_IO2
		.hps_io_hps_io_qspi_inst_IO3      (<connected-to-hps_io_hps_io_qspi_inst_IO3>),      //          .hps_io_qspi_inst_IO3
		.hps_io_hps_io_qspi_inst_SS0      (<connected-to-hps_io_hps_io_qspi_inst_SS0>),      //          .hps_io_qspi_inst_SS0
		.hps_io_hps_io_qspi_inst_CLK      (<connected-to-hps_io_hps_io_qspi_inst_CLK>),      //          .hps_io_qspi_inst_CLK
		.hps_io_hps_io_sdio_inst_CMD      (<connected-to-hps_io_hps_io_sdio_inst_CMD>),      //          .hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0       (<connected-to-hps_io_hps_io_sdio_inst_D0>),       //          .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1       (<connected-to-hps_io_hps_io_sdio_inst_D1>),       //          .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK      (<connected-to-hps_io_hps_io_sdio_inst_CLK>),      //          .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2       (<connected-to-hps_io_hps_io_sdio_inst_D2>),       //          .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3       (<connected-to-hps_io_hps_io_sdio_inst_D3>),       //          .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0       (<connected-to-hps_io_hps_io_usb1_inst_D0>),       //          .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1       (<connected-to-hps_io_hps_io_usb1_inst_D1>),       //          .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2       (<connected-to-hps_io_hps_io_usb1_inst_D2>),       //          .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3       (<connected-to-hps_io_hps_io_usb1_inst_D3>),       //          .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4       (<connected-to-hps_io_hps_io_usb1_inst_D4>),       //          .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5       (<connected-to-hps_io_hps_io_usb1_inst_D5>),       //          .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6       (<connected-to-hps_io_hps_io_usb1_inst_D6>),       //          .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7       (<connected-to-hps_io_hps_io_usb1_inst_D7>),       //          .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK      (<connected-to-hps_io_hps_io_usb1_inst_CLK>),      //          .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP      (<connected-to-hps_io_hps_io_usb1_inst_STP>),      //          .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR      (<connected-to-hps_io_hps_io_usb1_inst_DIR>),      //          .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT      (<connected-to-hps_io_hps_io_usb1_inst_NXT>),      //          .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim0_inst_CLK     (<connected-to-hps_io_hps_io_spim0_inst_CLK>),     //          .hps_io_spim0_inst_CLK
		.hps_io_hps_io_spim0_inst_MOSI    (<connected-to-hps_io_hps_io_spim0_inst_MOSI>),    //          .hps_io_spim0_inst_MOSI
		.hps_io_hps_io_spim0_inst_MISO    (<connected-to-hps_io_hps_io_spim0_inst_MISO>),    //          .hps_io_spim0_inst_MISO
		.hps_io_hps_io_spim0_inst_SS0     (<connected-to-hps_io_hps_io_spim0_inst_SS0>),     //          .hps_io_spim0_inst_SS0
		.hps_io_hps_io_spim1_inst_CLK     (<connected-to-hps_io_hps_io_spim1_inst_CLK>),     //          .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI    (<connected-to-hps_io_hps_io_spim1_inst_MOSI>),    //          .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO    (<connected-to-hps_io_hps_io_spim1_inst_MISO>),    //          .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0     (<connected-to-hps_io_hps_io_spim1_inst_SS0>),     //          .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX      (<connected-to-hps_io_hps_io_uart0_inst_RX>),      //          .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX      (<connected-to-hps_io_hps_io_uart0_inst_TX>),      //          .hps_io_uart0_inst_TX
		.hps_io_hps_io_gpio_inst_GPIO09   (<connected-to-hps_io_hps_io_gpio_inst_GPIO09>),   //          .hps_io_gpio_inst_GPIO09
		.hps_io_hps_io_gpio_inst_GPIO28   (<connected-to-hps_io_hps_io_gpio_inst_GPIO28>),   //          .hps_io_gpio_inst_GPIO28
		.hps_io_hps_io_gpio_inst_GPIO35   (<connected-to-hps_io_hps_io_gpio_inst_GPIO35>),   //          .hps_io_gpio_inst_GPIO35
		.hps_io_hps_io_gpio_inst_GPIO40   (<connected-to-hps_io_hps_io_gpio_inst_GPIO40>),   //          .hps_io_gpio_inst_GPIO40
		.hps_io_hps_io_gpio_inst_GPIO42   (<connected-to-hps_io_hps_io_gpio_inst_GPIO42>),   //          .hps_io_gpio_inst_GPIO42
		.hps_io_hps_io_gpio_inst_GPIO43   (<connected-to-hps_io_hps_io_gpio_inst_GPIO43>),   //          .hps_io_gpio_inst_GPIO43
		.hps_io_hps_io_gpio_inst_GPIO48   (<connected-to-hps_io_hps_io_gpio_inst_GPIO48>),   //          .hps_io_gpio_inst_GPIO48
		.hps_io_hps_io_gpio_inst_GPIO61   (<connected-to-hps_io_hps_io_gpio_inst_GPIO61>),   //          .hps_io_gpio_inst_GPIO61
		.hps_io_hps_io_gpio_inst_GPIO62   (<connected-to-hps_io_hps_io_gpio_inst_GPIO62>),   //          .hps_io_gpio_inst_GPIO62
		.hps_io_hps_io_gpio_inst_LOANIO00 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO00>), //          .hps_io_gpio_inst_LOANIO00
		.hps_io_hps_io_gpio_inst_LOANIO41 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO41>), //          .hps_io_gpio_inst_LOANIO41
		.hps_io_hps_io_gpio_inst_LOANIO51 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO51>), //          .hps_io_gpio_inst_LOANIO51
		.hps_io_hps_io_gpio_inst_LOANIO52 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO52>), //          .hps_io_gpio_inst_LOANIO52
		.hps_io_hps_io_gpio_inst_LOANIO53 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO53>), //          .hps_io_gpio_inst_LOANIO53
		.hps_io_hps_io_gpio_inst_LOANIO54 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO54>), //          .hps_io_gpio_inst_LOANIO54
		.hps_io_hps_io_gpio_inst_LOANIO55 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO55>), //          .hps_io_gpio_inst_LOANIO55
		.hps_io_hps_io_gpio_inst_LOANIO56 (<connected-to-hps_io_hps_io_gpio_inst_LOANIO56>), //          .hps_io_gpio_inst_LOANIO56
		.memory_mem_a                     (<connected-to-memory_mem_a>),                     //    memory.mem_a
		.memory_mem_ba                    (<connected-to-memory_mem_ba>),                    //          .mem_ba
		.memory_mem_ck                    (<connected-to-memory_mem_ck>),                    //          .mem_ck
		.memory_mem_ck_n                  (<connected-to-memory_mem_ck_n>),                  //          .mem_ck_n
		.memory_mem_cke                   (<connected-to-memory_mem_cke>),                   //          .mem_cke
		.memory_mem_cs_n                  (<connected-to-memory_mem_cs_n>),                  //          .mem_cs_n
		.memory_mem_ras_n                 (<connected-to-memory_mem_ras_n>),                 //          .mem_ras_n
		.memory_mem_cas_n                 (<connected-to-memory_mem_cas_n>),                 //          .mem_cas_n
		.memory_mem_we_n                  (<connected-to-memory_mem_we_n>),                  //          .mem_we_n
		.memory_mem_reset_n               (<connected-to-memory_mem_reset_n>),               //          .mem_reset_n
		.memory_mem_dq                    (<connected-to-memory_mem_dq>),                    //          .mem_dq
		.memory_mem_dqs                   (<connected-to-memory_mem_dqs>),                   //          .mem_dqs
		.memory_mem_dqs_n                 (<connected-to-memory_mem_dqs_n>),                 //          .mem_dqs_n
		.memory_mem_odt                   (<connected-to-memory_mem_odt>),                   //          .mem_odt
		.memory_mem_dm                    (<connected-to-memory_mem_dm>),                    //          .mem_dm
		.memory_oct_rzqin                 (<connected-to-memory_oct_rzqin>),                 //          .oct_rzqin
		.reset_reset_n                    (<connected-to-reset_reset_n>),                    //     reset.reset_n
		.ram_mm_address                   (<connected-to-ram_mm_address>),                   //    ram_mm.address
		.ram_mm_chipselect                (<connected-to-ram_mm_chipselect>),                //          .chipselect
		.ram_mm_clken                     (<connected-to-ram_mm_clken>),                     //          .clken
		.ram_mm_write                     (<connected-to-ram_mm_write>),                     //          .write
		.ram_mm_readdata                  (<connected-to-ram_mm_readdata>),                  //          .readdata
		.ram_mm_writedata                 (<connected-to-ram_mm_writedata>),                 //          .writedata
		.ram_mm_byteenable                (<connected-to-ram_mm_byteenable>),                //          .byteenable
		.ram_clk_clk                      (<connected-to-ram_clk_clk>),                      //   ram_clk.clk
		.ram_reset_reset                  (<connected-to-ram_reset_reset>)                   // ram_reset.reset
	);

