set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD0]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD1]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD2]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TXD3]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD0] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_MDIO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDIO]
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_MDC]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CTL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_emac1_inst_TX_CTL]
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RX_CLK] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD1] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD2] -to *
set_false_path -from [get_ports hps_io_hps_io_emac1_inst_RXD3] -to *
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO0]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO1]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO2]
set_false_path -from [get_ports hps_io_hps_io_qspi_inst_IO3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_IO3]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_SS0]
set_false_path -from * -to [get_ports hps_io_hps_io_qspi_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_CMD] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CMD]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D1]
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_CLK]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_sdio_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_sdio_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D1]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D4] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D4]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D5] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D5]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D6] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D6]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D7] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D7]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_CLK] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_STP]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_DIR] -to *
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_NXT] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spim0_inst_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_spim0_inst_MOSI]
set_false_path -from [get_ports hps_io_hps_io_spim0_inst_MISO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spim0_inst_SS0]
set_false_path -from * -to [get_ports hps_io_hps_io_spim1_inst_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_spim1_inst_MOSI]
set_false_path -from [get_ports hps_io_hps_io_spim1_inst_MISO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spim1_inst_SS0]
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO09] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO09]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO40] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO40]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO48] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO48]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO61] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO61]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_GPIO62] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_GPIO62]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO00] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO00]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO41] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO41]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO51] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO51]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO52] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO52]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO53] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO53]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO54] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO54]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO55] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO55]
set_false_path -from [get_ports hps_io_hps_io_gpio_inst_LOANIO56] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_gpio_inst_LOANIO56]